### ISSUE TITLE
mentioned http2 etc but possible to show https 1.1 and also h2 or something example?

### ISSUE THREAD

**Issue by sprappcom** [talostrading/sonic#125]
as titled

**Comment by sergiu128** [comment]
I'm going to start writing a small http1.1 codec soon, but I can't say when it'll be done. I made a ticket [here](https://github.com/talostrading/sonic/issues/127). Until then, you can try out writing codecs yourself. The simplest one is the [frame](https://github.com/talostrading/sonic/tree/master/codec/frame) codec. It uses a TCP transport to parse messages with a fixed-sized header and a variable-sized payload. The size of the payload is in the header.

For now, closing this issue.

**Comment by sprappcom** [comment]
@sergiu128 pls show a main.go file that will work with 
wrk 
http stress test tool.

thx
