### ISSUE TITLE
can someone pls show the tcp echo server showing request per second results?

### ISSUE THREAD

**Issue by sprappcom** [talostrading/sonic#126]
it's very difficult to use, tried 30 mins and cant get it to show req/s using chatgpt4

**Comment by sergiu128** [comment]
The TCP echo server example in `sonic/examples/echo` works fine (start `async_server` and then the `client`, you'll see the server echoing the message). 

If you want to calculate req/s, then you need to set up the server to read and write in a loop (and the client as well!). Here's an example on how you can do that: 

```go
b := make([]byte, 32)
var (
    onRead func(error, int)
    onWrite func(error, int)
)
onRead = func(err error, n int) {
    if err != nil {
        panic(err)
    }
    b = b[:n]
    fmt.Println("read:", string(b))
    conn.AsyncWrite(b, onWrite)
}
onWrite = func(err error, n int) {
    if err != nil {
        panic(err)
    }
    fmt.Println("echoed")
    conn.AsyncRead(b, onRead)
}

conn.AsyncRead(b, onRead) // this will be the first read

ioc.Run()
```

Feel free to make another example with `req/s` in `examples`. Would be good to have that either way as I have some changes incoming to remove the heap allocation of handlers in `file.go`. With that change the TCP client will not allocate anywhere so it should be way faster.
