### ISSUE TITLE
Build on arm64 fails due to undefined SYS_EPOLL_WAIT

### ISSUE THREAD

**Issue by csdenboer** [talostrading/sonic#134]
I am trying to build sonic for arm64 architecture (using `GOARCH=arm64 GOOS=linux go build -o bin/application cmd/server/main.go` - go 1.22), but it fails due to the error below:

`../../pkg/mod/github.com/talostrading/sonic@v0.6.0/internal/poll_linux.go:142:11: undefined: syscall.SYS_EPOLL_WAIT`

Is this as expected? Would it be better to use amd64?

**Comment by csdenboer** [comment]
From what I see `syscall` should be replaced with `golang.org/x/sys/unix`, but this is not really important. Closing it.

**Comment by sergiu128** [comment]
Oh yes! Using the `unix` package would be cleaner here but it still would not solve the problem. For example, `unix.EpollCreate` is still undefined on non-linux platforms.

**Comment by csdenboer** [comment]
I think it would be nice to arm64, because those instances are way cheaper considering hyperthreading is disabled by default.

**Comment by sergiu128** [comment]
> I think it would be nice to support arm64, because those instances are way cheaper considering hyperthreading is disabled by default.

arm64 is supported, you just can't cross-compile. You need to compile the program directly on your instance.

**Comment by csdenboer** [comment]
When trying to run code in other PR on c7g.4xlarge (arm64)

```bash
[root@ ~]# go build runner.go 
# github.com/talostrading/sonic/internal
go/pkg/mod/github.com/talostrading/sonic@v0.6.0/internal/poll_linux.go:142:11: undefined: syscall.SYS_EPOLL_WAIT
````

**Comment by sergiu128** [comment]
never used amazon linux. what does `man epoll_wait` say?

**Comment by sergiu128** [comment]
seems like a Go thing, don't how to fix:
```
[sergiu@LT-00142 binance]$ GOOS=linux GOARCH=amd64 go build main.go 
[sergiu@LT-00142 binance]$ GOOS=linux GOARCH=arm64 go build main.go 
# github.com/talostrading/sonic/internal
../../internal/poll_linux.go:151:11: undefined: syscall.SYS_EPOLL_WAIT
```

**Comment by sergiu128** [comment]
you're right, it works with the `unix` package. Apparently it was not ported to `syscall`. Tracking it [here](https://github.com/talostrading/sonic/issues/138). Thanks!
