### ISSUE TITLE
Don't heap-alloc on each read/write in `async_adapter`.

### ISSUE THREAD

**Issue by sergiu128** [talostrading/sonic#146]
Apply a18cfe8626f25e3451f480d8e23510eb37f438f9 and 08d3705f7b0635367d7af1c6576aa0a9e94f07c8 in `async_adapter.go`

**Comment by MaxMaeder** [comment]
Will try to tackle this weekend

**Comment by sergiu128** [comment]
> Will try to tackle this weekend

if you have any questions feel free to write them here or email me at `sergiu@tungsten.computer`. I'll reply quite fast on email this week, not so fast on github.
